### ISSUE TITLE
Skip existing while uploading?

### ISSUE THREAD

**Issue by juhi24** [CSCfi/ida2-command-line-tools#5]
From the documentation:

> `local_pathname` is the pathname of a folder or file on the local system which is to be uploaded, or the pathname on the local system to which a file will be downloaded (either a single data file or the zip file for a data folder). _Existing files will not be overwritten._

However, existing files seem to be overwritten while uploading. Is this a bug or a feature? It is not clear if the italized sentence refers to both uploads and downloads, or only downloads.

It would be useful, if data could be synced to IDA such that existing files would be skipped (based on either filenames or checksums).

**Comment by patrick-stickler-csc-fi** [comment]
Existing files in the IDA service are overwritten because we have, at present, no way to know if the local file has changed. Checksums are not maintained for files in staging, and even if the size is the same, that is no garuntee that there have been no changes.

We do not expect this behavior to change in the near future, but we will keep this issue in mind when considering future enhancements. 

Regards.

**Comment by patrick-stickler-csc-fi** [comment]
I will, however, update the documentation to clarify the behavior.
